[2023-04-25T07:55:44.656+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slack_integration.dummy_s_f_task manual__2023-04-25T07:55:44.161373+00:00 [queued]>
[2023-04-25T07:55:44.664+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slack_integration.dummy_s_f_task manual__2023-04-25T07:55:44.161373+00:00 [queued]>
[2023-04-25T07:55:44.665+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T07:55:44.665+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-25T07:55:44.666+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T07:55:44.674+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): dummy_s_f_task> on 2023-04-25 07:55:44.161373+00:00
[2023-04-25T07:55:44.679+0000] {standard_task_runner.py:55} INFO - Started process 1606 to run task
[2023-04-25T07:55:44.682+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'slack_integration', 'dummy_s_f_task', 'manual__2023-04-25T07:55:44.161373+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/Task4.py', '--cfg-path', '/tmp/tmp5cg2t1ve']
[2023-04-25T07:55:44.683+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask dummy_s_f_task
[2023-04-25T07:55:44.739+0000] {task_command.py:389} INFO - Running <TaskInstance: slack_integration.dummy_s_f_task manual__2023-04-25T07:55:44.161373+00:00 [running]> on host d51842477fac
[2023-04-25T07:55:44.790+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=slack_integration
AIRFLOW_CTX_TASK_ID=dummy_s_f_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T07:55:44.161373+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-25T07:55:44.161373+00:00
[2023-04-25T07:55:44.792+0000] {logging_mixin.py:137} INFO - 20
[2023-04-25T07:55:44.792+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Task4.py", line 12, in _random_fail
    raise Exception("number less than 50, so fail")
Exception: number less than 50, so fail
[2023-04-25T07:55:44.801+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=slack_integration, task_id=dummy_s_f_task, execution_date=20230425T075544, start_date=20230425T075544, end_date=20230425T075544
[2023-04-25T07:55:44.808+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 109 for task dummy_s_f_task (number less than 50, so fail; 1606)
[2023-04-25T07:55:44.858+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T07:55:44.880+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
