[2023-04-21T10:06:11.394+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing_2.insert_values scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2023-04-21T10:06:11.402+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing_2.insert_values scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2023-04-21T10:06:11.403+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:06:11.403+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-21T10:06:11.403+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:06:11.411+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): insert_values> on 2023-04-20 00:00:00+00:00
[2023-04-21T10:06:11.415+0000] {standard_task_runner.py:55} INFO - Started process 548 to run task
[2023-04-21T10:06:11.418+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing_2', 'insert_values', 'scheduled__2023-04-20T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Task1.py', '--cfg-path', '/tmp/tmpgc33pvfc']
[2023-04-21T10:06:11.420+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask insert_values
[2023-04-21T10:06:11.469+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing_2.insert_values scheduled__2023-04-20T00:00:00+00:00 [running]> on host cb97ea8540cf
[2023-04-21T10:06:11.516+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing_2
AIRFLOW_CTX_TASK_ID=insert_values
AIRFLOW_CTX_EXECUTION_DATE=2023-04-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-20T00:00:00+00:00
[2023-04-21T10:06:11.517+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        
[2023-04-21T10:06:11.525+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:06:11.629+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:06:11.634+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        , parameters: None
[2023-04-21T10:06:11.635+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-21T10:06:11.646+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=user_processing_2, task_id=insert_values, execution_date=20230420T000000, start_date=20230421T100611, end_date=20230421T100611
[2023-04-21T10:06:11.672+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-21T10:06:11.687+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
