[2023-04-21T10:06:14.231+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing_2.insert_values manual__2023-04-21T10:06:12.211703+00:00 [queued]>
[2023-04-21T10:06:14.240+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing_2.insert_values manual__2023-04-21T10:06:12.211703+00:00 [queued]>
[2023-04-21T10:06:14.241+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:06:14.242+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-21T10:06:14.243+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:06:14.252+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): insert_values> on 2023-04-21 10:06:12.211703+00:00
[2023-04-21T10:06:14.257+0000] {standard_task_runner.py:55} INFO - Started process 554 to run task
[2023-04-21T10:06:14.261+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing_2', 'insert_values', 'manual__2023-04-21T10:06:12.211703+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Task1.py', '--cfg-path', '/tmp/tmpdo9esd6r']
[2023-04-21T10:06:14.263+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask insert_values
[2023-04-21T10:06:14.318+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing_2.insert_values manual__2023-04-21T10:06:12.211703+00:00 [running]> on host cb97ea8540cf
[2023-04-21T10:06:14.371+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing_2
AIRFLOW_CTX_TASK_ID=insert_values
AIRFLOW_CTX_EXECUTION_DATE=2023-04-21T10:06:12.211703+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-21T10:06:12.211703+00:00
[2023-04-21T10:06:14.373+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        
[2023-04-21T10:06:14.381+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:06:14.489+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:06:14.494+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        , parameters: None
[2023-04-21T10:06:14.496+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-21T10:06:14.505+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=user_processing_2, task_id=insert_values, execution_date=20230421T100612, start_date=20230421T100614, end_date=20230421T100614
[2023-04-21T10:06:14.558+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-21T10:06:14.574+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
