[2023-04-21T10:18:05.286+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-21T10:18:03.552354+00:00 [queued]>
[2023-04-21T10:18:05.293+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-21T10:18:03.552354+00:00 [queued]>
[2023-04-21T10:18:05.294+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:18:05.294+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-21T10:18:05.295+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:18:05.303+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): insert_values> on 2023-04-21 10:18:03.552354+00:00
[2023-04-21T10:18:05.307+0000] {standard_task_runner.py:55} INFO - Started process 868 to run task
[2023-04-21T10:18:05.310+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'task_on_table', 'insert_values', 'manual__2023-04-21T10:18:03.552354+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/Task1.py', '--cfg-path', '/tmp/tmpstse2jud']
[2023-04-21T10:18:05.311+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask insert_values
[2023-04-21T10:18:05.363+0000] {task_command.py:388} INFO - Running <TaskInstance: task_on_table.insert_values manual__2023-04-21T10:18:03.552354+00:00 [running]> on host cb97ea8540cf
[2023-04-21T10:18:05.414+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=task_on_table
AIRFLOW_CTX_TASK_ID=insert_values
AIRFLOW_CTX_EXECUTION_DATE=2023-04-21T10:18:03.552354+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-21T10:18:03.552354+00:00
[2023-04-21T10:18:05.415+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        
[2023-04-21T10:18:05.424+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:18:05.530+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:18:05.535+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        , parameters: None
[2023-04-21T10:18:05.536+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-21T10:18:05.545+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=task_on_table, task_id=insert_values, execution_date=20230421T101803, start_date=20230421T101805, end_date=20230421T101805
[2023-04-21T10:18:05.564+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-21T10:18:05.585+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
